from Visuales.Botones.Botones import BotonAccionMain, BotonAccionSub
from Visuales.Combos.Combos import ComboForm
from Visuales.Dialogs.Dialogs import DialogElemento
from Visuales.Labels.Labels import LabelDialog, LabelIcono, LabelErrorC, LabelForm, LabelErrorL, LabelErrorForm, \
    LabelFormSub, LabelSubTitulo
from Visuales.Layouts.Layouts import LayoutVSimple, LayoutHCompacto, LayoutHCompactoAlt, LayoutHCompactoCen, \
    LayoutVCompacto
from Visuales.Lines.Lines import LineElemento, LineForm, CheckForm, LineFormIcon, TimeForm
from Visuales.Widgets.Widgets import EspacioH, LineFrame


class ProyectoAgregar(DialogElemento):
    def __init__(self):
        super().__init__("Registrar proyecto", 700, 505)
        imagen = LabelIcono("proyecto", 70)
        mainLayout = LayoutVSimple()
        tituloLayout = LayoutHCompactoCen()
        titulo = LabelDialog("Registrar proyecto")
        icono = LabelIcono("agregarElemento",30)
        tituloLayout.addSpacing(80)
        tituloLayout.addWidget(icono)
        tituloLayout.addSpacing(5)
        tituloLayout.addWidget(titulo)

        layoutCodigo = LayoutHCompacto()
        labelCodigo = LabelForm("Codigo", 150)
        lineCodigo = LineForm(50)
        errorCodigo = LabelErrorForm("")
        layoutCodigo.addWidget(labelCodigo)
        layoutCodigo.addWidget(lineCodigo)
        layoutCodigo.addWidget(errorCodigo)


        layoutNombre = LayoutHCompacto()
        labelNombre = LabelForm("Nombre del proyecto", 150)
        lineNombre = LineFormIcon(320, "mayuscula")
        errorNombre = LabelErrorForm("")
        layoutNombre.addWidget(labelNombre)
        layoutNombre.addWidget(lineNombre)
        layoutNombre.addWidget(errorNombre)


        layoutCliente = LayoutHCompacto()
        labelCliente = LabelForm("Cliente", 150)
        lineCliente = LineFormIcon(280, "carpetaAzul")
        errorCliente = LabelErrorForm("")
        layoutCliente.addWidget(labelCliente)
        layoutCliente.addWidget(lineCliente)
        layoutCliente.addWidget(errorCliente)

        layoutUbicacion = LayoutHCompacto()
        labelUbicacion = LabelForm("Ubicacion", 150)
        lineUbicacion= LineFormIcon(280, "carpetaAzul")
        errorUbicacion= LabelErrorForm("")
        layoutUbicacion.addWidget(labelUbicacion)
        layoutUbicacion.addWidget(lineUbicacion)
        layoutUbicacion.addWidget(errorUbicacion)

        layoutLocalidad = LayoutHCompacto()
        labelLocalidad = LabelForm("Localidad", 150)
        lineLocalidad = LineForm(280)
        errorLocalidad = LabelErrorForm("")
        layoutLocalidad.addWidget(labelLocalidad)
        layoutLocalidad.addWidget(lineLocalidad)
        layoutLocalidad.addWidget(errorLocalidad)

        layoutCosto = LayoutHCompacto()
        labelCosto = LabelForm("Costo a", 150)
        timeCosto = TimeForm(220)
        errorCosto= LabelErrorForm("")
        layoutCosto.addWidget(labelCosto)
        layoutCosto.addWidget(timeCosto)
        layoutCosto.addWidget(errorCosto)

        layoutJornada = LayoutHCompacto()
        labelJornada = LabelForm("Jornada Laboral", 150)
        lineJornada = LineForm(150)
        errorJornada = LabelErrorForm("")
        layoutJornada.addWidget(labelJornada)
        layoutJornada.addWidget(lineJornada)
        layoutJornada.addWidget(errorJornada)

        layoutGrupo = LayoutHCompacto()
        labelGrupo = LabelForm("Grupo para analizar", 150)
        lineGrupo = LineForm(220)
        errorGrupo = LabelErrorForm("")
        layoutGrupo.addWidget(labelGrupo)
        layoutGrupo.addWidget(lineGrupo)
        layoutGrupo.addWidget(errorGrupo)

        layoutMoneda = LayoutHCompacto()
        labelMoneda = LabelForm("Moneda", 150)
        comboMoneda = ComboForm(150)
        errorMoneda = LabelErrorForm("")
        checkMoneda = CheckForm("Los precios de insumo incluyen IGV")
        layoutMonedaSub = LayoutVCompacto()
        layoutMonedaSub.addWidget(comboMoneda)
        layoutMonedaSub.addSpacing(5)
        layoutMonedaSub.addWidget(checkMoneda)
        layoutMoneda.addWidget(labelMoneda)
        layoutMoneda.addLayout(layoutMonedaSub)
        layoutMoneda.addWidget(errorMoneda)

        layoutMembrete = LayoutHCompacto()
        labelMembrete = LabelForm("Membrete", 150)
        lineMembreteR = LineForm(157)
        lineMembreteL = LineForm(157)
        errorMembrete = LabelErrorForm("")
        labelMembreteL = LabelFormSub("Izquierda")
        labelMembreteR = LabelFormSub("Derecha")
        layoutMembrete.addWidget(labelMembrete)

        layoutMembreteL = LayoutVCompacto()
        layoutMembreteL.addWidget(lineMembreteL)
        layoutMembreteL.addWidget(labelMembreteL)
        layoutMembreteR = LayoutVCompacto()
        layoutMembreteR.addWidget(lineMembreteR)
        layoutMembreteR.addWidget(labelMembreteR)

        layoutMembrete.addLayout(layoutMembreteL)
        layoutMembrete.addSpacing(5)
        layoutMembrete.addLayout(layoutMembreteR)
        layoutMembrete.addWidget(errorMembrete)

        agregar = BotonAccionMain("Agregar")
        cancelar = BotonAccionSub("Cancelar")
        cancelar.clicked.connect(self.close)
        botonLayout = LayoutHCompactoAlt()
        botonLayout.addWidget(agregar)
        botonLayout.addSpacing(5)
        botonLayout.addWidget(cancelar)

        mainTop = LayoutVCompacto()
        mainTop.addLayout(tituloLayout)
        mainTop.addSpacing(10)
        mainTop.addLayout(layoutCodigo)

        mainImagen = LayoutHCompacto()
        mainImagen.addLayout(mainTop)
        mainImagen.addWidget(imagen)

        mainLayout.addLayout(mainImagen)
        mainLayout.addSpacing(10)
        mainLayout.addWidget(LineFrame())
        mainLayout.addSpacing(10)
        mainLayout.addLayout(layoutNombre)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutCliente)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutUbicacion)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutLocalidad)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutCosto)
        mainLayout.addSpacing(10)
        mainLayout.addWidget(LineFrame())
        mainLayout.addSpacing(10)
        mainLayout.addLayout(layoutGrupo)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutJornada)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutMoneda)
        mainLayout.addSpacing(9)
        mainLayout.addLayout(layoutMembrete)
        mainLayout.addSpacing(10)

        mainLayout.addLayout(botonLayout)
        self.setLayout(mainLayout)

class ProyectoEditar(DialogElemento):
    def __init__(self):
        super().__init__("Editar proyecto", 700, 505)
        imagen = LabelIcono("proyecto", 70)
        mainLayout = LayoutVSimple()
        tituloLayout = LayoutHCompactoCen()
        titulo = LabelDialog("Editar proyecto")
        icono = LabelIcono("editarElemento",30)
        tituloLayout.addSpacing(80)
        tituloLayout.addWidget(icono)
        tituloLayout.addSpacing(5)
        tituloLayout.addWidget(titulo)

        layoutCodigo = LayoutHCompacto()
        labelCodigo = LabelForm("Codigo", 150)
        lineCodigo = LineForm(50)
        errorCodigo = LabelErrorForm("")
        layoutCodigo.addWidget(labelCodigo)
        layoutCodigo.addWidget(lineCodigo)
        layoutCodigo.addWidget(errorCodigo)

        layoutNombre = LayoutHCompacto()
        labelNombre = LabelForm("Nombre del proyecto", 150)
        lineNombre = LineFormIcon(320, "mayuscula")
        errorNombre = LabelErrorForm("")
        layoutNombre.addWidget(labelNombre)
        layoutNombre.addWidget(lineNombre)
        layoutNombre.addWidget(errorNombre)

        layoutCliente = LayoutHCompacto()
        labelCliente = LabelForm("Cliente", 150)
        lineCliente = LineFormIcon(280, "carpetaAzul")
        errorCliente = LabelErrorForm("")
        layoutCliente.addWidget(labelCliente)
        layoutCliente.addWidget(lineCliente)
        layoutCliente.addWidget(errorCliente)

        layoutUbicacion = LayoutHCompacto()
        labelUbicacion = LabelForm("Ubicacion", 150)
        lineUbicacion= LineFormIcon(280, "carpetaAzul")
        errorUbicacion= LabelErrorForm("")
        layoutUbicacion.addWidget(labelUbicacion)
        layoutUbicacion.addWidget(lineUbicacion)
        layoutUbicacion.addWidget(errorUbicacion)

        layoutLocalidad = LayoutHCompacto()
        labelLocalidad = LabelForm("Localidad", 150)
        lineLocalidad = LineForm(280)
        errorLocalidad = LabelErrorForm("")
        layoutLocalidad.addWidget(labelLocalidad)
        layoutLocalidad.addWidget(lineLocalidad)
        layoutLocalidad.addWidget(errorLocalidad)

        layoutCosto = LayoutHCompacto()
        labelCosto = LabelForm("Costo a", 150)
        timeCosto = TimeForm(220)
        errorCosto= LabelErrorForm("")
        layoutCosto.addWidget(labelCosto)
        layoutCosto.addWidget(timeCosto)
        layoutCosto.addWidget(errorCosto)

        layoutJornada = LayoutHCompacto()
        labelJornada = LabelForm("Jornada Laboral", 150)
        lineJornada = LineForm(150)
        errorJornada = LabelErrorForm("")
        layoutJornada.addWidget(labelJornada)
        layoutJornada.addWidget(lineJornada)
        layoutJornada.addWidget(errorJornada)

        layoutGrupo = LayoutHCompacto()
        labelGrupo = LabelForm("Grupo para analizar", 150)
        lineGrupo = LineForm(220)
        errorGrupo = LabelErrorForm("")
        layoutGrupo.addWidget(labelGrupo)
        layoutGrupo.addWidget(lineGrupo)
        layoutGrupo.addWidget(errorGrupo)

        layoutMoneda = LayoutHCompacto()
        labelMoneda = LabelForm("Moneda", 150)
        comboMoneda = ComboForm(150)
        errorMoneda = LabelErrorForm("")
        checkMoneda = CheckForm("Los precios de insumo incluyen IGV")
        layoutMonedaSub = LayoutVCompacto()
        layoutMonedaSub.addWidget(comboMoneda)
        layoutMonedaSub.addSpacing(5)
        layoutMonedaSub.addWidget(checkMoneda)
        layoutMoneda.addWidget(labelMoneda)
        layoutMoneda.addLayout(layoutMonedaSub)
        layoutMoneda.addWidget(errorMoneda)

        layoutMembrete = LayoutHCompacto()
        labelMembrete = LabelForm("Membrete", 150)
        lineMembreteR = LineForm(157)
        lineMembreteL = LineForm(157)
        errorMembrete = LabelErrorForm("")
        labelMembreteL = LabelFormSub("Izquierda")
        labelMembreteR = LabelFormSub("Derecha")
        layoutMembrete.addWidget(labelMembrete)

        layoutMembreteL = LayoutVCompacto()
        layoutMembreteL.addWidget(lineMembreteL)
        layoutMembreteL.addWidget(labelMembreteL)
        layoutMembreteR = LayoutVCompacto()
        layoutMembreteR.addWidget(lineMembreteR)
        layoutMembreteR.addWidget(labelMembreteR)

        layoutMembrete.addLayout(layoutMembreteL)
        layoutMembrete.addSpacing(5)
        layoutMembrete.addLayout(layoutMembreteR)
        layoutMembrete.addWidget(errorMembrete)

        agregar = BotonAccionMain("Guardar")
        cancelar = BotonAccionSub("Cancelar")
        cancelar.clicked.connect(self.close)
        botonLayout = LayoutHCompactoAlt()
        botonLayout.addWidget(agregar)
        botonLayout.addSpacing(5)
        botonLayout.addWidget(cancelar)

        mainTop = LayoutVCompacto()
        mainTop.addLayout(tituloLayout)
        mainTop.addSpacing(10)
        mainTop.addLayout(layoutCodigo)

        mainImagen = LayoutHCompacto()
        mainImagen.addLayout(mainTop)
        mainImagen.addWidget(imagen)

        mainLayout.addLayout(mainImagen)
        mainLayout.addSpacing(10)
        mainLayout.addWidget(LineFrame())
        mainLayout.addSpacing(10)
        mainLayout.addLayout(layoutNombre)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutCliente)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutUbicacion)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutLocalidad)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutCosto)
        mainLayout.addSpacing(10)
        mainLayout.addWidget(LineFrame())
        mainLayout.addSpacing(10)
        mainLayout.addLayout(layoutGrupo)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutJornada)
        mainLayout.addSpacing(5)
        mainLayout.addLayout(layoutMoneda)
        mainLayout.addSpacing(9)
        mainLayout.addLayout(layoutMembrete)
        mainLayout.addSpacing(10)

        mainLayout.addLayout(botonLayout)
        self.setLayout(mainLayout)

class ProyectoEliminar(DialogElemento):
    def __init__(self):
        super().__init__("Eliminar proyecto", 400, 215)
        mainLayout = LayoutVSimple()
        icono = LabelIcono("eliminarElemento", 40)
        titulo = LabelDialog("¿Estas seguro que deseas eliminar este proyecto?")
        subtitulo = LabelSubTitulo("Escribe SI para confirmar")

        confirmar = LineElemento()
        error = LabelErrorC("")
        guardar = BotonAccionMain("Eliminar")
        cancelar = BotonAccionSub("Cancelar")
        cancelar.clicked.connect(self.close)
        botonLayout = LayoutHCompactoAlt()
        botonLayout.addWidget(guardar)
        botonLayout.addSpacing(5)
        botonLayout.addWidget(cancelar)

        mainLayout.addWidget(icono)
        mainLayout.addSpacing(5)
        mainLayout.addWidget(titulo)
        mainLayout.addSpacing(15)
        mainLayout.addWidget(subtitulo)
        mainLayout.addSpacing(5)
        mainLayout.addWidget(confirmar)
        mainLayout.addSpacing(10)
        mainLayout.addWidget(error)
        mainLayout.addSpacing(15)
        mainLayout.addLayout(botonLayout)

        self.setLayout(mainLayout)